fashion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recommand.urls")),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

recommand/urls.py
from django.urls import path
from . import views

app_name = "recommand"

urlpatterns = [
    path("", views.main, name="main"),
    
    path("man/", views.man, name="man"),
    path("woman/", views.woman, name="woman"),

    path("img_detail/<path:img_url>/", views.img_detail, name="img_detail"),  # <path:img_url>로 변경
    path("img_detail_w/<path:img_url>/", views.img_detail_w, name="img_detail_w"),

    path("clothe_info/<path:related_img_url>/", views.clothe_info, name = "clothe_info"),
    path("clothe_info_w/<path:related_img_url>/", views.clothe_info_w, name = "clothe_info_w"),
    
    # 남자
    path("아메카지/", views.image_list, {'style': '아메카지'}, name="아메카지"),
    path("캐주얼/", views.image_list, {'style': '캐주얼'}, name="캐주얼"),
    path("시크/", views.image_list, {'style': '시크'}, name="시크"),
    path("댄디/", views.image_list, {'style': '댄디'}, name="댄디"),  
    path("비즈니스캐주얼/", views.image_list, {'style': '비즈니스캐주얼'}, name="비즈니스캐주얼"),
    path("고프고어/", views.image_list, {'style': '고프코어'}, name="고프코어"),  
    path("스포티/", views.image_list, {'style': '스포티'}, name="스포티"),  
    path("스트릿/", views.image_list, {'style': '스트릿'}, name="스트릿"),
    
    # 여기부터 여자
    path("캐주얼_w/", views.image_list_w, {'style': '캐주얼'}, name="캐주얼_w"),
    path("시크_w/", views.image_list_w, {'style': '시크'}, name="시크_w"),
    path("비즈니스캐주얼_w/", views.image_list_w, {'style': '비즈니스캐주얼'}, name="비즈니스캐주얼_w"),
    path("걸리시_w/", views.image_list_w, {'style': '걸리시'}, name="걸리시_w"),  
    path("로맨틱_w/", views.image_list_w, {'style': '로맨틱'}, name="로맨틱_w"),
    path("스포티_w/", views.image_list_w, {'style': '스포티'}, name="스포티_w"),  
    path("스트릿_w/", views.image_list_w, {'style': '스트릿'}, name="스트릿_w"),  
]

templates/base_main.html
{% load static %}
<!DOCTYPE HTML>
<html lang="ko">
    <head>
        <title>Fashion</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="description" content="">
        <meta name="keywords" csontent="">
        <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
        <link href="//fonts.googleapis.com/css?family=Arimo:400,700" rel="stylesheet" type="text/css"> <!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="{% static 'js/skel.min.js' %}"></script>
        <script src="{% static 'js/skel-panels.min.js' %}"></script>
        <script src="{% static 'js/init.js' %}"></script>
            
        <link rel="stylesheet" href="{% static 'css/skel-noscript.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/style-desktop.css' %}">
        <!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]--><!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
        {% block head %}{% endblock %}
    </head>

    <body>
        {% block base_content %}{% endblock%}
        	<!-- Footer -->
        <div id="footer">
            <div class="container">
                <div class="row">
                    <div class="6u">
                        <section><h2>MAN's STYLE</h2>
                            <ul class="default">                        
                                <li><a href="{%url 'recommand:아메카지' %}">아메카지</a></li>
                                <li><a href="{%url 'recommand:캐주얼' %}">캐주얼</a></li>
                                <li><a href="{%url 'recommand:시크' %}">시크</a></li>
                                <li><a href="{%url 'recommand:댄디' %}">댄디</a></li>
                                <li><a href="{%url 'recommand:비즈니스캐주얼' %}">포멀</a></li>
                                <li><a href="{%url 'recommand:고프코어' %}">고프코어</a></li>
                                <li><a href="{%url 'recommand:스포티' %}">스포티</a></li>
                                <li><a href="{%url 'recommand:스트릿' %}">스트릿</a></li>
                            </ul></section></div>
                    <div class="6u">
                        <section><h2>WOMAN's STYLE</h2>
                            <ul class="default">
                                <li><a href="{%url 'recommand:캐주얼_w' %}">캐주얼</a></li>
                                <li><a href="{%url 'recommand:시크_w' %}">시크</a></li>
                                <li><a href="{%url 'recommand:비즈니스캐주얼_w' %}">포멀</a></li>
                                <li><a href="{%url 'recommand:걸리시_w' %}">걸리시</a></li>
                                <li><a href="{%url 'recommand:로맨틱_w' %}">로맨틱</a></li>
                                <li><a href="{%url 'recommand:스포티_w' %}">스포티</a></li>
                                <li><a href="{%url 'recommand:스트릿_w' %}">스트릿</a></li>
                            </ul>
                        </section>
                    </div>
                </div>
            </div>
        </div>

        <!-- Copyright -->
        <div id="copyright">
            <div class="container">
                <p>Passion makes Fashion</p>
            </div>
        </div>
    </body>
</html>

templates/clothes_detail.html
{% extends 'base_main.html' %}

{% block head %}
<style>
    .results-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around;
    }
    .result-item {
        margin: 10px;
        text-align: center;
    }
    .result-item img {
        width: 200px;  /* 적절한 크기로 조정하세요 */
        height: auto;
    }
</style>
{% endblock %}

{% block base_content %}
<body>
    <!-- Header -->
    <div id="header">
        <!-- Logo -->
        <div id="logo">
            <h1><a href="{% url 'recommand:main' %}">Fashion</a></h1>
            <span>For your style</span>
        </div>
    </div>
    <br> <br>
    <style>
        .image {
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
    <br> <br>
    <h4 style="color:white; margin-top: 10px; text-align: center;"> <!-- 수정된 부분 -->
        <a href="https://www.musinsa.com/app/goods/{{clothe_id}}">
            {{ clothe_title }}
        </a>
    </h4>
    <div class="image">
        <a href="https://www.musinsa.com/app/goods/{{clothe_id}}">
            <img src="https://image.msscdn.net/images/goods_img/{{ related_img_url }}" style="width:200px; height:300px;" alt="Clothe Image">
        </a>
        <br> <br>
    </div>
    <br> <br>
    <div class="image">
        <span style = "color:white; text-align: center; font-size: larger;">How about these clothes?</span>
    </div>
    <div class="results-container">
        {% for text_title, text_url, text_id in results %}
            <div class="result-item">
                <a href = "https://www.musinsa.com/app/goods/{{ text_id }}">
                    <img src="https://image.msscdn.net/images/goods_img/{{ text_url }}" style="width:200px; height:300px;" alt="Image">
                 </a>
                <h4 style="color:white; margin-top: 10px; text-align: center;">
                    <a href = "https://www.musinsa.com/app/goods/{{ text_id }}">
                        <h4>{{ text_title }}</h4>
                    </a>
                </h4>
            </div>
        {% endfor %}
    </div>
</body>
{% endblock %}

templates/image_list.html
{% extends 'base_main.html' %}

{% block base_content %}
<body>
   <!-- Header -->
   <div id="header">
      
         <!-- Logo -->
         <div id="logo">
            <h1><a href="{% url 'recommand:main' %}">Fashion</a></h1>
            <span>For your style</span>
         </div>
        </div>
    </div>


    <div>
        
        <style>
            .image-list {
                list-style-type: none;
                padding: 120px;
            }
            .image-list li {
                display: inline-block;
                margin: 10px;
            }
            .image-list li img {
                width: 160px;
                height: 300px;
            }
            .pagination {
                text-align: center;
                color:white;
            }

            .pagination a {
                color: white;
                text-decoration: none; /* 링크 밑줄 제거 */
            }

        </style>
    </div>
    <div id = "logo">
        <br>
        <br>
        <br>
        <span style = "color:white; text-align: center; font-size: larger;">{{ style }}</span>
        <ul class="image-list">
            {% for url in page_obj %}
                <li>
                    <a href="{% url 'recommand:img_detail' img_url=url %}">
                        <img src="{{ url }}" alt="Image">
                    </a>
                </li>
            {% endfor %}

        </ul>
    </div>
    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
{% endblock %}

templates/image_list_w.html
{% extends 'base_main.html' %}

{% block base_content %}
<body>
   <!-- Header -->
   <div id="header">
      
         <!-- Logo -->
         <div id="logo">
            <h1><a href="{% url 'recommand:main' %}">Fashion</a></h1>
            <span>For your style</span>
         </div>
        </div>
    </div>


    <div>
        
        <style>
            .image-list {
                list-style-type: none;
                padding: 120px;
            }
            .image-list li {
                display: inline-block;
                margin: 10px;
            }
            .image-list li img {
                width: 160px;
                height: 300px;
            }
            .pagination {
                text-align: center;
                color:white;
            }

            .pagination a {
                color: white;
                text-decoration: none; /* 링크 밑줄 제거 */
            }

        </style>
    </div>
    <div id = "logo">
        <br>
        <br>
        <br>
        <span style = "color:white; text-align: center; font-size: larger;">{{ style }}</span>
        <ul class="image-list">
        {% for url in page_obj %}
            <li>
                <a href="{% url 'recommand:img_detail_w' img_url=url %}">
                    <img src="{{ url }}" alt="Image">
                </a>
            </li>
        {% endfor %}

    </div>
    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
{% endblock %}

templates/img_detail.html
{% extends 'base_main.html' %}

{% block base_content %}
<body>
   <!-- Header -->
   <div id="header">
      
         <!-- Logo -->
         <div id="logo">
            <h1><a href="{% url 'recommand:main' %}">Fashion</a></h1>
            <span>For your style</span>
         </div>
        </div>
    </div>
    
    <style>
        .image {
            display: flex;
            justify-content: center;
            align-items: center;   
        }
    </style>
    <br><br>

    <div class="image">
        <br><br>
        

        <img src="{{ img_id }}" style="width:200px; height:300px;" alt="Similar Image">
    </div>    
        <br> <br> <br>
        <p style = "font-size: larger; text-align: center; color:white">Clothes Worn</p>
        <br> <br>

    <div class="image">
        {% if related_img_urls %}
            {% for related_img_url in related_img_urls %}
                <a href = "{% url 'recommand:clothe_info' related_img_url=related_img_url %}">
                    <img src="https://image.msscdn.net/images/goods_img/{{ related_img_url }}" style="width:200px; height:250px; align-items: center; padding: 10px;" alt="Related Image">
                </a>
            {% endfor %}
        {% else %}
            <p>No related images found.</p>
        {% endif %}
    </div>
    </div>
</body>
<br> <br>
{% endblock %}

templates/img_detail_w.html
{% extends 'base_main.html' %}

{% block base_content %}
<body>
   <!-- Header -->
   <div id="header">
      
         <!-- Logo -->
         <div id="logo">
            <h1><a href="{% url 'recommand:main' %}">Fashion</a></h1>
            <span>For your style</span>
         </div>
        </div>
    </div>
    <br><br>
    
    <style>
        .image {
            display: flex;
            justify-content: center;
            align-items: center;
            
        }
    </style>

    
    <div class="image">
    <br><br>
    
        <img src="{{ img_id }}" style="width:200px; height:300px;" alt="Similar Image">
    </div>
    <br> <br> <br>
    <p style = "font-size: larger; text-align: center; color:white">Clothes Worn</p>
    <br> <br>
    <div class="image">
        {% if related_img_urls %}
            {% for related_img_url in related_img_urls %}
                <a href = "{% url 'recommand:clothe_info_w' related_img_url=related_img_url %}">
                    <img src="https://image.msscdn.net/images/goods_img/{{ related_img_url }}" style="width:200px; height:250px; align-items: center; padding: 10px;"  alt="Related Image">
                </a>
            {% endfor %}
        {% else %}
            <p>No related images found.</p>
        {% endif %}
    </div>
</body>
<br> <br>
{%endblock%}

templates/main.html
{% extends 'base_main.html' %}

{% block base_content %}
<body class="homepage">
   <!-- Header -->
   <div id="header">
      <div class="container"> 
         <img src="../media/images/1.jpg" min-width = "1200px">
         
         <!-- Logo -->
         <div id="logo">
            <h1><a href="{% url 'recommand:main' %}">Fashion</a></h1>
            <span>For your style</span>
         </div>
         
         <!-- Nav -->
         <nav id="nav">
            <ul>
               <li class="active"><a href="{% url 'recommand:main' %}">Homepage</a></li>
               <li><a href="{% url 'recommand:man' %}">MAN</a></li>
               <li><a href="{% url 'recommand:woman' %}">WOMAN</a></li>
            </ul>
         </nav>
      </div>
   </div>
   

   <!-- Footer -->
   <div id="featured">

      <div class="ManWoman" style="display: flex; justify-content: space-around;">
         <style>

            .mw {
               display: flex;
               flex-direction: column;
               justify-content: center;
               text-align: center;
               margin: 0 auto; /* 수평 가운데 정렬을 위해 추가 */
               max-width: 400px; /* 가운데 정렬의 폭을 조정할 수 있습니다. */
            }

            .mw h2, .mw p {
               margin: 0; /* 기본 마진 제거 */
            }

            .mw img {
               margin: auto; /* 이미지를 수평 가운데 정렬하기 위해 */
            }
         </style>
         

         <div class="row">
            
            <div class = "mw">
               <h2 >MAN</h2>
               <a href="{% url 'recommand:man' %}" class="image full">
                  <img id="image_id_man" src="../media/images/man/1.jpg"  width="314" height="500">
               </a>
               
               <p><a href="{% url 'recommand:man' %}" class="button">More Details</a></p>
            </div>
            
            <div class = "mw">
               <h2>WOMAN</h2>
               <a href="{% url 'recommand:woman' %}" class="image full">
                  <img id="image_id_woman" src="../media/images/woman/1.jpg" width="314" height="500">
               </a>
               
               <p><a href="{% url 'recommand:woman' %}" class="button">More Details</a></p>
            </div>
            
            <script language="javascript">
               
               var obTimeOutMan;
               var obTimeOutWoman;

               var ObjectArrayMan = [
                  "../media/images/man/1.jpg",
                  "../media/images/man/2.jpg",
                  "../media/images/man/3.jpg",
                  "../media/images/man/4.jpg",
                  "../media/images/man/5.jpg",
                  "../media/images/man/6.jpg",
                  "../media/images/man/7.jpg",
                  "../media/images/man/8.jpg",
                  "../media/images/man/9.jpg",
                  "../media/images/man/10.jpg",
               ];

               var ObjectArrayWoman = [
                  "../media/images/woman/1.jpg",
                  "../media/images/woman/2.jpg",
                  "../media/images/woman/3.jpg",
                  "../media/images/woman/4.jpg",
                  "../media/images/woman/5.jpg",
                  "../media/images/woman/6.jpg",
                  "../media/images/woman/7.jpg",
                  "../media/images/woman/8.jpg",
                  "../media/images/woman/9.jpg",
                  "../media/images/woman/10.jpg",
               ];
               var nObjectCntMan = 0;
               var nObjectCntWoman = 0;
            
               function ShowDefaultRotateMan() {
                  nObjectCntMan++;
                  if (nObjectCntMan < ObjectArrayMan.length) {
                     document.getElementById("image_id_man").src = ObjectArrayMan[nObjectCntMan];
                     obTimeOutMan = setTimeout(ShowDefaultRotateMan, 5000);
                  } else {
                     clearTimeout(obTimeOutMan);
                  }
               }
            
               function ShowDefaultRotateWoman() {
                  nObjectCntWoman++;
                  if (nObjectCntWoman < ObjectArrayWoman.length) {
                     document.getElementById("image_id_woman").src = ObjectArrayWoman[nObjectCntWoman];
                     obTimeOutWoman = setTimeout(ShowDefaultRotateWoman, 5000);
                  } else {
                     clearTimeout(obTimeOutWoman);
                  }
               }
            
               function startAnimation() {
                  obTimeOutMan = setTimeout(ShowDefaultRotateMan, 100);
                  obTimeOutWoman = setTimeout(ShowDefaultRotateWoman, 100);
               }
            
               window.onload = startAnimation;
            </script>

         </div>
      </div>
   </div>
</body>
{% endblock%}